import Navbar from '@/components/navbar'


export const metadata = {
title: 'Next.js',
description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
return (
  <html lang="e n">
    <head>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width" />
      <meta name="description" content={metadata.description} />
      <meta name="generator" content={`Next.js ${metadata.version || 'unknown'}`} />
      </head>
     
    <body>
      <Navbar />
      {children}
      </body>
  </html>
)
}
