import styles from '@/styles/globals.css'

export const metadata = {
title: 'Next.js',
description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
return (
  <html lang="e n">
    <body>{children}</body>
  </html>
)
}
